sudo: required
dist: trusty
group: deprecated-2017Q4
language: c
arch:
        packages:
                - wget
                - perl
                - zip
                - unzip
        script:
                - "./build.sh"
script:
        - curl -s https://raw.githubusercontent.com/sreimers/arch-travis/master/arch-travis.sh | bash
